### ISSUE TITLE
It does not work (win8.1)

### ISSUE THREAD

**Issue by AquaGen** [XaF/TraktForVLC#12] opened 2015-05-07 05:49 UTC
I do not know English, use a translator. Maybe I misread the instructions.
What I did:
1. I inserted pin in config.ini file
2. I replaced windows_batch\config.bat at it:

set python=C:\Python34\pythonw.exe
set tfv_py=C:\TraktForVLC-master\TraktForVLC.py
set tfv_data=C:\TraktForVLC-master\
set tfv_config=C:\TraktForVLC-master\
set tfv_pidfile=C:\TraktForVLC-master\TraktForVLC.pid
set vlc_path=C:\Program Files\VideoLAN\VLC\vlc.exe
3. Run the file set_registry_keys.bat
4. Run the file start_process.bat

when I run the file appears start_process command line, which is then closed and nothing happens.Can I move or delete a folder with the program. Means the program files are not used.
the text of the command line

Microsoft Windows [Version 6.3.9600]
(c) Корпорация Майкрософт (Microsoft Corporation), 2013. Все права защищены.
C:\Windows\system32>cd C:\TraktForVLC-master\windows_batch
C:\TraktForVLC-master\windows_batch>start_process.bat
C:\TraktForVLC-master\windows_batch>cd /D C:\TraktForVLC-master\windows_batch\
C:\TraktForVLC-master\windows_batch>call ".\config.bat"
C:\TraktForVLC-master\windows_batch>set python=C:\Python34\pythonw.exe
C:\TraktForVLC-master\windows_batch>set tfv_py=C:\TraktForVLC-master\TraktForVLC
.py
C:\TraktForVLC-master\windows_batch>set tfv_data=C:\TraktForVLC-master\
C:\TraktForVLC-master\windows_batch>set tfv_config=C:\TraktForVLC-master\
C:\TraktForVLC-master\windows_batch>set tfv_pidfile=C:\TraktForVLC-master\TraktF
orVLC.pid
C:\TraktForVLC-master\windows_batch>set vlc_path=C:\Program Files\VideoLAN\VLC\v
lc.exe
C:\TraktForVLC-master\windows_batch>set ip=localhost
C:\TraktForVLC-master\windows_batch>set port=4222
C:\TraktForVLC-master\windows_batch>set formats=avi
C:\TraktForVLC-master\windows_batch>set vlc_opts=--extraintf=rc --rc-host=\"loca
lhost\":\"4222\" --rc-quiet
C:\TraktForVLC-master\windows_batch>start "TraktForVLC" C:\Python34\pythonw.exe
C:\TraktForVLC-master\TraktForVLC.py --datadir C:\TraktForVLC-master\ --config C
:\TraktForVLC-master\ --pidfile C:\TraktForVLC-master\TraktForVLC.pid

And watching movies on the site is not marked. Please help me to install this program.

**Comment by XaF** [comment] 2015-05-10 01:34
If you open a windows console and run the following:
```sh
C:\Python34\pythonw.exe
C:\TraktForVLC-master\TraktForVLC.py --datadir C:\TraktForVLC-master\ --config C
:\TraktForVLC-master\ --pidfile C:\TraktForVLC-master\TraktForVLC.pid
```

What does it say ?

**Comment by AquaGen** [comment] 2015-05-10 18:54
C:\Windows\system32>C:\Python34\pythonw.exe

C:\Windows\system32>
C:\Windows\system32>C:\TraktForVLC-master\TraktForVLC.py --datadir C:\TraktForVL
C-master\ --config C:\TraktForVLC-master\ --pidfile C:\TraktForVLC-master\TraktF
orVLC.pid
Traceback (most recent call last):
  File "C:\TraktForVLC-master\TraktForVLC.py", line 60, in <module>
    import tvdb_api
  File "C:\TraktForVLC-master\tvdb_api\__init__.py", line 60, in <module>
    from tvdb_ui import BaseUI, ConsoleUI
ImportError: No module named 'tvdb_ui'

C:\Windows\system32>

**Comment by Loewkie** [comment] 2015-05-11 13:02
Ok so this is what I did;

- Downloaded VLC 2.2.0
- Extracted .ZIP to C:\TraktforVLC
- Removed .default extension from config.ini and config.bat in order to make them editable
- Edited the following entries in the .bat file:
{
     - set python=C:\Python27\pythonw.exe
     - set tfv_py=C:\TraktforVLC\TraktForVLC.py
     - set tfv_data=C:\TraktforVLC\
     - set tfv_config=C:\TraktforVLC\
     - set tfv_pidfile=C:\TraktforVLC\TraktForVLC.pid
     - set vlc_path=C:\Program Files (x86)\VideoLAN\VLC\vlc.exe
     - set ip=localhost
     - set port=4222
     - set formats=avi, mkv, mov, mp4, wmv, ts, mpg
     - set vlc_opts=--extraintf=rc --rc-host=\"%ip%\":\"%port%\" --rc-quiet
}
 - Saved and closed the config.bat file
 - Ran set_registry_keys.bat (No errors)
 - Got pin from site and pasted it in the config.ini file
 - Saved and closed config.ini
 - Didn't change anything in start_process.bat, ran it. (No errors)

For me it also doesn't work, when running the C:\TraktforVLC\TraktForVLC.py I get the following (I have it installed in a different folder as you can see:

{
Traceback (most recent call last):
File "C:\TraktforVLC\TraktforCLV.py", line 38, in <module>
from pkg_resources import parse_version
ImportError: No module named pkg_resources
}

So that's that.

**Comment by XaF** [comment] 2015-05-11 18:28
@AquaGen, can you tell me the version of Python you're using?

@Loewkie, your issue is not linked at all to this one. You're just missing the pkg_resources module. You can find it [here, in setuptools](https://bitbucket.org/pypa/setuptools#rst-header-installation-instructions). Follow the instructions to install it and you'll have pkg_resources. It is sometimes included with Python, sometimes it's not... I don't follow the pattern!

**Comment by Loewkie** [comment] 2015-05-11 21:19
Ok, so I did that. Now that error is gone, but I get this one (which I find very strange)

C:\Users\Luc>C:\TraktforVLC\TraktForVLC.py --datadir C:\TraktforVLC\ --config C
2015-05-11 23:18:11,200::TraktForVLC::ERROR::Config file C\config.ini not found,
 exiting.

**Comment by XaF** [comment] 2015-05-11 21:20
Where is your config file?

**Comment by Loewkie** [comment] 2015-05-11 21:21
In the TraktforVLC master folder, just as it was in the .ZIP file. That's why I find it strange that it cannot find it.

**Comment by XaF** [comment] 2015-05-11 21:24
The ```--config``` option is used to define the path where your config file can be found. In your case, ```C``` means your config file will be found in a ```C``` directory near your current position. Try using that: ```C:\TraktforVLC\TraktForVLC.py --datadir C:\TraktforVLC\ --config C:\TraktforVLC\``` or even just ```C:\TraktforVLC\TraktForVLC.py``` as by default the directory of ```TraktForVLC.py``` will be used.

**Comment by Loewkie** [comment] 2015-05-11 21:26
Sorry I am so bad at this, just your average joe when it comes to programming unfortunately :(

Now I have this:

C:\Users\Luc>C:\TraktforVLC\TraktForVLC.py
C:\TraktforVLC\requests\packages\urllib3\util\ssl_.py:79: InsecurePlatformWarnin
g: A true SSLContext object is not available. This prevents urllib3 from configu
ring SSL appropriately and may cause certain SSL connections to fail. For more i
nformation, see https://urllib3.readthedocs.org/en/latest/security.html#insecure
platformwarning.
  InsecurePlatformWarning
C:\Python27\lib\site-packages\setuptools-15.2-py2.7.egg\pkg_resources\__init__.p
y:197: RuntimeWarning: You have iterated over the result of pkg_resources.parse_
version. This is a legacy behavior which is inconsistent with the new version cl
ass introduced in setuptools 8.0. In most cases, conversion to a tuple is unnece
ssary. For comparison of versions, sort the Version instances directly. If you h
ave another use case requiring the tuple, please file a bug with the setuptools
project describing that need.

**Comment by XaF** [comment] 2015-05-11 21:29
You should look at other issues when new problem appears, and if you don't find your answer open new issues. This would help other users find answers to their problems without having to ask again the same questions!
The first warning has been discussed in issue #11 and the second one in #13. You should find your answers there, even though they are warnings so ```TraktForVLC``` should work properly!

**Comment by Loewkie** [comment] 2015-05-11 21:30
Sorry again, and thank you for your great help!

**Comment by AquaGen** [comment] 2015-05-12 07:28
I downloaded the latest version from the official site. 3.4.3  Release date: 2015-02-23

**Comment by XaF** [comment] 2015-05-13 18:59
Can you do ```python -c "import tvdb_api; print(dir(tvdb_api))"``` from the ```TraktForVLC``` directory?

**Comment by AquaGen** [comment] 2015-05-15 19:53
C:\TraktForVLC-master>python -c "import tvdb_api; print(dir(tvdb_api))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\TraktForVLC-master\tvdb_api\__init__.py", line 60, in <module>
    from tvdb_ui import BaseUI, ConsoleUI
ImportError: No module named 'tvdb_ui'

**Comment by XaF** [comment] 2015-05-15 20:01
Ok, I'm just trying to assess what's happening. Still from the ```TraktForVLC``` directory:
- ```ls -Als tvdb_api```
- ```python -c "import sys; print(sys.path)"```

**Comment by AquaGen** [comment] 2015-06-30 01:07
I installed Python 2.7. Now another message. 

C:\Windows\system32>C:\TraktForVLC-master\TraktForVLC.py --datadir C:\TraktForVL
C-master\ --config C:\TraktForVLC-master\ --pidfile C:\TraktForVLC-master\TraktF
orVLC.pid
C:\Python27\lib\site-packages\pkg_resources\__init__.py:197: RuntimeWarning: You
 have iterated over the result of pkg_resources.parse_version. This is a legacy
behavior which is inconsistent with the new version class introduced in setuptoo
ls 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of v
ersions, sort the Version instances directly. If you have another use case requi
ring the tuple, please file a bug with the setuptools project describing that ne
ed.
  stacklevel=1,

**Comment by XaF** [comment] 2015-06-30 18:34
The nothing happens part is normal: TraktForVLC on windows "stays alive" but does not show anything, as there is no real daemon mode available directly from Python. It is why you should start it using the starting script in that case.

The fact that you see that warning has been addressed in #17 and I just pushed the commit c2f4625c0f17fb5ed22dcc8779d537aabccd1ee9 that should prevent that warning from happening. It however is not a problem that should prevent TraktForVLC from running.

**Comment by AquaGen** [comment] 2015-06-30 22:55
C:\TraktForVLC-master\windows_batch>start_process.bat

C:\TraktForVLC-master\windows_batch>cd /D C:\TraktForVLC-master\windows_batch\

C:\TraktForVLC-master\windows_batch>call ".\config.bat"

C:\TraktForVLC-master\windows_batch>set python=C:\Python34\pythonw.exe

C:\TraktForVLC-master\windows_batch>set tfv_py=C:\TraktForVLC-master\TraktForVLC
.py

C:\TraktForVLC-master\windows_batch>set tfv_data=C:\TraktForVLC-master\

C:\TraktForVLC-master\windows_batch>set tfv_config=C:\TraktForVLC-master\

C:\TraktForVLC-master\windows_batch>set tfv_pidfile=C:\TraktForVLC-master\TraktF
orVLC.pid

C:\TraktForVLC-master\windows_batch>set vlc_path=C:\Program Files\VideoLAN\VLC\v
lc.exe

C:\TraktForVLC-master\windows_batch>set ip=localhost

C:\TraktForVLC-master\windows_batch>set port=4222

C:\TraktForVLC-master\windows_batch>set formats=avi

C:\TraktForVLC-master\windows_batch>set vlc_opts=--extraintf=rc --rc-host=\"loca
lhost\":\"4222\" --rc-quiet

C:\TraktForVLC-master\windows_batch>start "TraktForVLC" C:\Python34\pythonw.exe
C:\TraktForVLC-master\TraktForVLC.py --datadir C:\TraktForVLC-master\ --config C
:\TraktForVLC-master\ --pidfile C:\TraktForVLC-master\TraktForVLC.pid

C:\TraktForVLC-master\windows_batch>

still nothing happens. what to do?

**Comment by XaF** [comment] 2015-07-01 02:12
Well, have you verified the python process is not running in background?
Because from what you show me, it seems `TraktForVLC` is working.

**Comment by AquaGen** [comment] 2015-07-01 21:42
what the name of the process? python process in Task Manager does not. and nothing on the site is not marked, when I run a movie for viewing

**Comment by XaF** [comment] 2015-07-01 22:04
Can you run TraktForVLC in debug mode by using `start_debug_process.bat` ?
You should have on the screen what's happening.

**Comment by AquaGen** [comment] 2015-07-02 05:04
C:\TraktForVLC-master\windows_batch>start_debug_process.bat

C:\TraktForVLC-master\windows_batch>cd /D C:\TraktForVLC-master\windows_batch\

C:\TraktForVLC-master\windows_batch>call ".\config.bat"

C:\TraktForVLC-master\windows_batch>set python=C:\Python34\pythonw.exe

C:\TraktForVLC-master\windows_batch>set tfv_py=C:\TraktForVLC-master\TraktForVLC
.py

C:\TraktForVLC-master\windows_batch>set tfv_data=C:\TraktForVLC-master\

C:\TraktForVLC-master\windows_batch>set tfv_config=C:\TraktForVLC-master\

C:\TraktForVLC-master\windows_batch>set tfv_pidfile=C:\TraktForVLC-master\TraktF
orVLC.pid

C:\TraktForVLC-master\windows_batch>set vlc_path=C:\Program Files\VideoLAN\VLC\v
lc.exe

C:\TraktForVLC-master\windows_batch>set ip=localhost

C:\TraktForVLC-master\windows_batch>set port=4222

C:\TraktForVLC-master\windows_batch>set formats=avi

C:\TraktForVLC-master\windows_batch>set vlc_opts=--extraintf=rc --rc-host=\"loca
lhost\":\"4222\" --rc-quiet

C:\TraktForVLC-master\windows_batch>start "TraktForVLC" C:\Python34\pythonw.exe
C:\TraktForVLC-master\TraktForVLC.py --datadir C:\TraktForVLC-master\ --config C
:\TraktForVLC-master\ --pidfile C:\TraktForVLC-master\TraktForVLC.pid --debug --
small-timers

C:\TraktForVLC-master\windows_batch>


you tell me how to run this program or not? >>:< 
I have 2 months trying to start it. During the time that I spent on the setup program I could manually check online all the movies in my life looked.

**Comment by XaF** [comment] 2015-07-02 05:10
I'm not sure being unpleasant to someone who's trying to help you is a good way to solve your problem. I'm not on your computer, I don't have windows, it's therefore difficult for me to put a diagnostic on your problem, even more when you stop answering for one and a half month. Moreover, providing a tool as `TraktForVLC` is a service that you get for free. Whether you decide to use it or to manually check online all the movies you looked in your life is your choice, but please stay classy and respectful. Remember before everything that "This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE".

Once that has been said, do you see any file in the "logs" directory of `TraktForVLC` ? If you have a `TraktForVLC-DEBUG.log` file, this should give us information about what's happening.

**Comment by AquaGen** [comment] 2015-07-02 05:24
I forgot to change the Python 2.7 in the settings.
now I see the process of a python. but the site does not change anything. tell me how it should work?
I open the video file Thorne.01x03.Sleepyhead.ep3.[AlexFilm].avi
localhost:4222

>status change: ( new input: file:///C:/Users/%D0%98%D0%B2/Downloads/Thorne%20%28AlexFilm%29/Thorne.01x03.Sleepyhead.ep3.%5BAlexFilm%5D.avi )
status change: ( play state: 3 )
РќРµРёР·РІРµСЃС‚РЅР°СЏ РєРѕРјР°РЅРґР° `GET'. Р’РІРµРґРёС‚Рµ `help' РґР»СЏ СЃРїСЂР°РІРєРё.
+----[ РљРѕРјР°РЅРґС‹ РґРёСЃС‚Р°РЅС†РёРѕРЅРЅРѕРіРѕ СѓРїСЂР°РІР»РµРЅРёСЏ ]
| 
| add XYZ  . . . . . . . .  РґРѕР±Р°РІРёС‚СЊ XYZ РІ РїР»РµР№Р»РёСЃС‚
| enqueue XYZ  . . . . . .  РґРѕР±Р°РІРёС‚СЊ XYZ РІ РѕС‡РµСЂРµРґСЊ РїР»РµР№Р»РёСЃС‚Р°
| playlist . . . . . . . .  РїРѕРєР°Р·Р°С‚СЊ РёРјРµСЋС‰РёРµСЃСЏ РїРѕР·РёС†РёРё РІ РїР»РµР№Р»РёСЃС‚Рµ
| play . . . . . . . . . .  РІРѕСЃРїСЂРѕРёР·РІРµСЃС‚Рё РїРѕС‚РѕРє
| stop . . . . . . . . . .  РѕСЃС‚Р°РЅРѕРІРёС‚СЊ РїРѕС‚РѕРє
| next . . . . . . . . . .  СЃР»РµРґСѓСЋС‰Р°СЏ РїРѕР·РёС†РёСЏ РІ РїР»РµР№Р»РёСЃС‚Рµ
| prev . . . . . . . . . .  РїСЂРµРґС‹РґСѓС‰Р°СЏ РїРѕР·РёС†РёСЏ РІ РїР»РµР№Р»РёСЃС‚Рµ
| goto . . . . . . . . . .  РїРµСЂРµР№С‚Рё Рє РїРѕР·РёС†РёРё РїРѕ РёРЅРґРµРєСЃСѓ
| repeat [on|off] . . . . . РІРєР»./РІС‹РєР». РїРѕРІС‚РѕСЂР° РїРѕР·РёС†РёР№ РІ РїР»РµР№Р»РёСЃС‚Рµ
| loop [on|off] . . . . . . РІРєР»./РІС‹РєР». Р·Р°С†РёРєР»РёРІР°РЅРёРµ РїР»РµР№Р»РёСЃС‚Р°
| random [on|off] . . . . . РІРєР»./РІС‹РєР». СЃР»СѓС‡Р°Р№РЅС‹Р№ РїРѕСЂСЏРґРѕРє
| clear . . . . . . . . . . РѕС‡РёСЃС‚РёС‚СЊ РїР»РµР№Р»РёСЃС‚
| status . . . . . . . . .  С‚РµРєСѓС‰РёР№ СЃС‚Р°С‚СѓСЃ РїР»РµР№Р»РёСЃС‚Р°
| title [X]  . . . . . . .  Р·Р°РґР°С‚СЊ/РїРѕР»СѓС‡РёС‚СЊ Р·Р°РіР»Р°РІРёРµ С‚РµРєСѓС‰РµР№ РїРѕР·РёС†РёРё
| title_n  . . . . . . . .  СЃР»РµРґСѓСЋС‰РµРµ Р·Р°РіР»Р°РІРёРµ РІ С‚РµРєСѓС‰РµР№ РїРѕР·РёС†РёРё
| title_p  . . . . . . . .  РїСЂРµРґС‹РґСѓС‰РµРµ Р·Р°РіР»Р°РІРёРµ РІ С‚РµРєСѓС‰РµР№ РїРѕР·РёС†РёРё
| chapter [X]  . . . . . .  Р·Р°РґР°С‚СЊ/РїРѕР»СѓС‡РёС‚СЊ РіР»Р°РІСѓ С‚РµРєСѓС‰РµР№ РїРѕР·РёС†РёРё
| chapter_n  . . . . . . .  СЃР»РµРґСѓСЋС‰Р°СЏ РіР»Р°РІР° РІ С‚РµРєСѓС‰РµР№ РїРѕР·РёС†РёРё
| chapter_p  . . . . . . .  РїСЂРµРґС‹РґСѓС‰Р°СЏ РіР»Р°РІР° РІ С‚РµРєСѓС‰РµР№ РїРѕР·РёС†РёРё
| 


but the site can not see that I look Thorne

**Comment by XaF** [comment] 2015-07-02 05:27
Do you have a full `TraktForVLC` log file to show me? What you pasted is just part of the log related to VLC, but the DEBUG log file should contain many more information.

**Comment by AquaGen** [comment] 2015-07-03 01:10
Something started to work. Now the series has appeared on the site while viewing, but not abolished as the viewed after viewing.

2015-07-03 06:51:28,727::VLCRemote::DEBUG::<- Received: Dark.Matter.S01E04.WEB-DL.Kerob.mkv
2015-07-03 06:51:28,729::VLCRemote::DEBUG::-> Sending: get_time
2015-07-03 06:51:28,729::VLCRemote::DEBUG::<- Received: 54
2015-07-03 06:51:28,729::TraktForVLC::INFO::Dark Matter - 1x04 state : 2%
2015-07-03 06:51:28,729::TraktForVLC::DEBUG::main::Video: {'duration': 2615, 'show_imdbid': u'tt4159076', 'episode': u'4', 'title': u'Dark Matter', 'tv': True, 'imdbid': u'tt4381250', 'percentage': 2, 'year': u'2015-06-13', 'season': u'1'}
2015-07-03 06:51:28,729::TraktForVLC::DEBUG::main::This video is scrobbled : False
2015-07-03 06:51:28,729::TraktForVLC::DEBUG::main::Trying to mark Dark Matter - 1x04 watching on Trakt...
2015-07-03 06:51:28,729::TraktClient::DEBUG::Sending POST to https://api-v2launch.trakt.tv/scrobble/start data {"app_date": "2015-04-14", "progress": 2, "app_version": "1.3.0-rc1", "episode": {"season": "1", "number": "4"}, "show": {"ids": {"imdb": "tt4159076"}}}
2015-07-03 06:51:28,730::TraktClient::DEBUG::{"app_date": "2015-04-14", "progress": 2, "app_version": "1.3.0-rc1", "episode": {"season": "1", "number": "4"}, "show": {"ids": {"imdb": "tt4159076"}}}
2015-07-03 06:51:28,730::requests.packages.urllib3.connectionpool::INFO::Starting new HTTPS connection (1): api-v2launch.trakt.tv
2015-07-03 06:51:49,651::requests.packages.urllib3.connectionpool::DEBUG::"POST /scrobble/start HTTP/1.1" 201 262
2015-07-03 06:51:49,657::TraktForVLC::INFO::Dark Matter - 1x04 is currently watching on Trakt...
2015-07-03 06:51:54,658::VLCRemote::DEBUG::-> Sending: is_playing
2015-07-03 06:51:57,660::TraktForVLC::ERROR::An unknown error occurred
Traceback (most recent call last):
  File "C:\TraktForVLC-master\TraktForVLC.py", line 397, in run
    self.main()
  File "C:\TraktForVLC-master\TraktForVLC.py", line 434, in main
    vlcStatus = vlc.is_playing()
  File "C:\TraktForVLC-master\vlcrc\__init__.py", line 152, in is_playing
    playing = self._command('is_playing', fn_re, raw=True)
  File "C:\TraktForVLC-master\vlcrc\__init__.py", line 109, in _command
    'Pattern: %s\nReceived: %s' % (return_re.pattern, cmd_ret))
VLCBadReturn: Pattern: ^(?!status change:)>?\s*(?P<playing>\d+)
?


Received: 
2015-07-03 06:52:02,663::VLCRemote::DEBUG::-> Sending: is_playing
2015-07-03 06:52:05,664::TraktForVLC::ERROR::An unknown error occurred
Traceback (most recent call last):
  File "C:\TraktForVLC-master\TraktForVLC.py", line 397, in run
    self.main()
  File "C:\TraktForVLC-master\TraktForVLC.py", line 434, in main
    vlcStatus = vlc.is_playing()
  File "C:\TraktForVLC-master\vlcrc\__init__.py", line 152, in is_playing
    playing = self._command('is_playing', fn_re, raw=True)
  File "C:\TraktForVLC-master\vlcrc\__init__.py", line 109, in _command
    'Pattern: %s\nReceived: %s' % (return_re.pattern, cmd_ret))
VLCBadReturn: Pattern: ^(?!status change:)>?\s*(?P<playing>\d+)
?

below repeated the same thing over and over again

...
Received: 
2015-07-03 07:55:09,450::VLCRemote::DEBUG::-> Sending: is_playing
2015-07-03 07:55:12,451::TraktForVLC::ERROR::An unknown error occurred
Traceback (most recent call last):
  File "C:\TraktForVLC-master\TraktForVLC.py", line 397, in run
    self.main()
  File "C:\TraktForVLC-master\TraktForVLC.py", line 434, in main
    vlcStatus = vlc.is_playing()
  File "C:\TraktForVLC-master\vlcrc\__init__.py", line 152, in is_playing
    playing = self._command('is_playing', fn_re, raw=True)
  File "C:\TraktForVLC-master\vlcrc\__init__.py", line 109, in _command
    'Pattern: %s\nReceived: %s' % (return_re.pattern, cmd_ret))
VLCBadReturn: Pattern: ^(?!status change:)>?\s*(?P<playing>\d+)
?

Received: 
2015-07-03 07:55:17,460::VLCRemote::DEBUG::-> Sending: is_playing
2015-07-03 07:55:19,792::TraktForVLC::ERROR::An unknown error occurred
Traceback (most recent call last):
  File "C:\TraktForVLC-master\TraktForVLC.py", line 397, in run
    self.main()
  File "C:\TraktForVLC-master\TraktForVLC.py", line 434, in main
    vlcStatus = vlc.is_playing()
  File "C:\TraktForVLC-master\vlcrc\__init__.py", line 152, in is_playing
    playing = self._command('is_playing', fn_re, raw=True)
  File "C:\TraktForVLC-master\vlcrc\__init__.py", line 106, in _command
    index, match, cmd_ret = self.cnx.expect([return_re], self.timeout)
  File "C:\Python27\lib\telnetlib.py", line 655, in expect
    return self._expect_with_select(list, timeout)
  File "C:\Python27\lib\telnetlib.py", line 755, in _expect_with_select
    self.fill_rawq()
  File "C:\Python27\lib\telnetlib.py", line 576, in fill_rawq
    buf = self.sock.recv(50)
error: [Errno 10054] 
2015-07-03 07:55:26,801::TraktForVLC::INFO::Could not find VLC running at localhost:4222
2015-07-03 07:55:26,801::TraktForVLC::DEBUG::Make sure your VLC player is running with --extraintf=rc --rc-host=localhost:4222 --rc-quiet
Traceback (most recent call last):
  File "C:\TraktForVLC-master\TraktForVLC.py", line 407, in main
    vlc = VLCRemote(self.vlc_ip, self.vlc_port)
  File "C:\TraktForVLC-master\vlcrc\__init__.py", line 38, in __init__
    self.cnx = telnetlib.Telnet(hostname, port)
  File "C:\Python27\lib\telnetlib.py", line 211, in __init__
    self.open(host, port, timeout)
  File "C:\Python27\lib\telnetlib.py", line 227, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "C:\Python27\lib\socket.py", line 575, in create_connection
    raise err
error: [Errno 10061] Ю嫫��饠󱲠즭
2015-07-03 07:55:26,802::TraktClient::DEBUG::Sending POST to https://api-v2launch.trakt.tv/scrobble/start data {"app_date": "2015-04-14", "progress": 99.99, "app_version": "1.3.0-rc1", "episode": {"season": "1", "number": "4"}, "show": {"ids": {"imdb": "tt4159076"}}}
2015-07-03 07:55:26,802::TraktClient::DEBUG::{"app_date": "2015-04-14", "progress": 99.99, "app_version": "1.3.0-rc1", "episode": {"season": "1", "number": "4"}, "show": {"ids": {"imdb": "tt4159076"}}}
2015-07-03 07:55:26,803::requests.packages.urllib3.connectionpool::INFO::Starting new HTTPS connection (1): api-v2launch.trakt.tv
2015-07-03 07:55:27,736::requests.packages.urllib3.connectionpool::DEBUG::"POST /scrobble/start HTTP/1.1" 201 268
2015-07-03 07:55:27,740::TraktForVLC::DEBUG::reset cache view status (None)

**Comment by RaviOnline** [comment] 2015-07-09 15:00
Hi,

I'm facing the same issue on Windows 8.1. I ran the commands directly on the console as asked above and got the same *ImportError: No module named 'tvdb_ui'* error. I had downloaded the latest Python version **3.4.3** since the installation guide said it supports 3.x as well.

I'm not so keen on installing version 2.x as I plan on learning Python in the near future and would wanna work with the latest one. Is TraktForVLC a legacy app that runs on Python 2 mainly but sort of should run on Python 3 as well? If you can confirm that it works with **3.4.3** without any problems on Linux then I would like to debug and provide you the logs to see what's the issue. Let me know.

Regards,
Ravi

**Comment by XaF** [comment] 2015-07-28 00:01
@AquaGen It seems it's linked to VLC, I'm sorry you're having so much troubles using `TraktForVLC`...

@RaviOnline I can confirm it works for 3.4.3 (tests have been performed on travis with 3.4.2 - not any big changes between 3.4.2 and 3.4.3 as far as `TraktForVLC` is concerned - and AppVeyor with 3.4.3, and I use it on my own computer on Linux with 3.4.3). If you want to look at what's going on with that issue, it would be better to open a specific issue with a clear title about that error. I'll do my best to help you debug that!

**Comment by JimiC** [comment] 2015-11-28 15:27
I think this issue can be closed for the following reasons:
1. About AquaGen issue, from his last report I conclude that TracktForVLC is working as expected. There is a delay between the action taken on VLC and what is shown in trakt.tv (which is normal).

2. About RaviOnline issue, I have tested TraktForVLC on Python (x64) versions 3.4.2, 3.4.3 and 3.5 and all is well.

**Comment by XaF** [comment] 2015-11-28 23:52
Thanks for your feedback @JimiC !

**Closed by XaF** 2015-11-28 23:52 UTC
Labels: OS Windows
